title: "My Portfolio"
description: "Personal website with About, Work Experience, and Projects"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

show_downloads: false









